version: '3'
    
services:
  db:
    image: postgres
  web:
    build: .
    command: python todo/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todo
    ports:
      - "8000:8000"
    depends_on:
      - db